"use server";
import type { Metadata } from "next";
import { AccountClient } from "./account-client";
import { t } from "@/lib/t";

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: t("seo.account_title"),
    robots: { index: false },
    alternates: {
      canonical: "/hesabim",
    },
  };
}

export default async function AccountPage() {
  return (
    <AccountClient
      translations={{
        my_account: t("account.my_account"),
        profile: t("account.profile"),
        change_password: t("account.change_password"),
        addresses: t("account.addresses"),
        first_name: t("account.first_name"),
        last_name: t("account.last_name"),
        email: t("account.email"),
        phone: t("account.phone"),
        birth_day: t("account.birth_day"),
        gender: t("account.gender"),
        gender_male: t("account.gender_male"),
        gender_female: t("account.gender_female"),
        gender_others: t("account.gender_others"),
        profile_updated: t("account.profile_updated"),
        old_password: t("account.old_password"),
        new_password: t("account.new_password"),
        confirm_password: t("account.confirm_password"),
        password_changed: t("account.password_changed"),
        passwords_not_match: t("account.passwords_not_match"),
        delete_account: t("account.delete_account"),
        delete_account_confirm: t("account.delete_account_confirm"),
        delete_account_message: t("account.delete_account_message"),
        delete_yes: t("account.delete_yes"),
        delete_no: t("account.delete_no"),
        wishlist: t("account.wishlist"),
        no_wishlist: t("account.no_wishlist"),
        recently_viewed: t("account.recently_viewed"),
        no_recently_viewed: t("account.no_recently_viewed"),
        clear_history: t("account.clear_history"),
        no_addresses: t("checkout.no_addresses"),
        address_saved: t("checkout.address_saved"),
        add_address: t("checkout.add_address"),
        address_type: t("checkout.address_type"),
        address_type_home: t("checkout.address_type_home"),
        address_type_office: t("checkout.address_type_office"),
        address_type_others: t("checkout.address_type_others"),
        address_title: t("checkout.address_title"),
        address_field: t("checkout.address_field"),
        address_email: t("checkout.address_email"),
        address_phone: t("checkout.address_phone"),
        address_road: t("checkout.address_road"),
        address_house: t("checkout.address_house"),
        address_floor: t("checkout.address_floor"),
        address_postal: t("checkout.address_postal"),
        set_default: t("checkout.set_default"),
        // Order translations
        my_orders: t("order.my_orders"),
        order_number: t("order.order_number"),
        order_date: t("order.order_date"),
        view_detail: t("order.view_detail"),
        cancel_order: t("order.cancel_order"),
        no_orders: t("order.no_orders"),
        cancel_confirm: t("order.cancel_confirm"),
        cancel_confirm_message: t("order.cancel_confirm_message"),
        cancel_yes: t("order.cancel_yes"),
        cancel_no: t("order.cancel_no"),
        status_pending: t("order.status_pending"),
        status_confirmed: t("order.status_confirmed"),
        status_processing: t("order.status_processing"),
        status_pickup: t("order.status_pickup"),
        status_shipped: t("order.status_shipped"),
        status_delivered: t("order.status_delivered"),
        status_cancelled: t("order.status_cancelled"),
        status_on_hold: t("order.status_on_hold"),
        filter_all: t("order.filter_all"),
        items_count: t("order.items_count"),
        // Support translations
        support: t("support.support"),
        new_ticket: t("support.new_ticket"),
        ticket_title: t("support.ticket_title"),
        ticket_subject: t("support.ticket_subject"),
        ticket_priority: t("support.ticket_priority"),
        priority_low: t("support.priority_low"),
        priority_medium: t("support.priority_medium"),
        priority_high: t("support.priority_high"),
        priority_urgent: t("support.priority_urgent"),
        status_open: t("support.status_open"),
        status_closed: t("support.status_closed"),
        no_tickets: t("support.no_tickets"),
        view_conversation: t("support.view_conversation"),
        type_message: t("support.type_message"),
        resolve_ticket: t("support.resolve_ticket"),
        // Common
        home: t("common.home"),
        loading: t("common.loading"),
        error: t("common.error"),
        save: t("common.save"),
        cancel: t("common.cancel"),
        delete: t("common.delete"),
        edit: t("common.edit"),
        logout: t("common.logout"),
        currency: t("common.currency"),
        previous: t("common.previous"),
        next: t("common.next"),
        search: t("common.search"),
      }}
    />
  );
}
