CREATE TABLE IF NOT EXISTS ads_banners (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  position VARCHAR(64) NOT NULL,
  title VARCHAR(190) NOT NULL,
  advertiser VARCHAR(160) NULL,
  notes VARCHAR(500) NULL,
  type ENUM('image','code') NOT NULL DEFAULT 'image',
  source_type ENUM('custom','listing','seller','code') NOT NULL DEFAULT 'custom',
  lifecycle_status ENUM('draft','proposal','reserved','payment_pending','scheduled','live','completed','cancelled','problem','archived') NOT NULL DEFAULT 'draft',
  payment_status ENUM('unpaid','partial','paid','waived','refunded','cancelled') NOT NULL DEFAULT 'unpaid',
  payment_override TINYINT NOT NULL DEFAULT 0,
  payment_override_reason VARCHAR(500) NULL,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  payment_due_at DATETIME(3) NULL,
  payment_grace_hours INT NOT NULL DEFAULT 72,
  payment_reminder_sent_at DATETIME(3) NULL,
  invoice_number VARCHAR(120) NULL,
  invoice_url VARCHAR(512) NULL,
  contract_file_url VARCHAR(512) NULL,
  creative_file_url VARCHAR(512) NULL,
  creative_template VARCHAR(64) NOT NULL DEFAULT 'image',
  creative_config JSON NULL,
  quality_override_reason VARCHAR(500) NULL,
  quality_checked_at DATETIME(3) NULL,
  listing_id CHAR(36) NULL,
  seller_id CHAR(36) NULL,
  sponsorship_id INT NULL,
  deal_id INT NULL,
  image_url VARCHAR(512) NULL,
  alt VARCHAR(255) NULL,
  link_url VARCHAR(500) NULL,
  link_target VARCHAR(20) NOT NULL DEFAULT '_blank',
  rel VARCHAR(64) NOT NULL DEFAULT 'sponsored nofollow noopener',
  code TEXT NULL,
  caption VARCHAR(300) NULL,
  cta_label VARCHAR(60) NULL,
  device ENUM('all','desktop','mobile') NOT NULL DEFAULT 'all',
  desktop_row INT NOT NULL DEFAULT 1,
  desktop_columns INT NOT NULL DEFAULT 1,
  weight INT NOT NULL DEFAULT 1,
  display_order INT NOT NULL DEFAULT 0,
  is_active TINYINT NOT NULL DEFAULT 0,
  start_at DATETIME(3) NULL,
  end_at DATETIME(3) NULL,
  reservation_expires_at DATETIME(3) NULL,
  sales_owner VARCHAR(160) NULL,
  cancellation_reason VARCHAR(500) NULL,
  archived_at DATETIME(3) NULL,
  impressions INT NOT NULL DEFAULT 0,
  clicks INT NOT NULL DEFAULT 0,
  impression_limit INT NULL,
  click_limit INT NULL,
  daily_impression_limit INT NULL,
  daily_impressions INT NOT NULL DEFAULT 0,
  daily_impressions_date DATE NULL,
  visitor_daily_impression_limit INT NOT NULL DEFAULT 3,
  visitor_campaign_impression_limit INT NOT NULL DEFAULT 20,
  experiment_key VARCHAR(96) NULL,
  creative_variant VARCHAR(32) NULL,
  auto_optimize TINYINT NOT NULL DEFAULT 0,
  minimum_optimization_impressions INT NOT NULL DEFAULT 1000,
  performance_status ENUM('learning','normal','low','winner') NOT NULL DEFAULT 'learning',
  report_email VARCHAR(255) NULL,
  weekly_report_enabled TINYINT NOT NULL DEFAULT 0,
  weekly_report_sent_at DATETIME(3) NULL,
  closing_report_sent_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX ads_banners_position_idx (position,is_active,display_order),
  INDEX ads_banners_active_idx (is_active),
  INDEX ads_banners_layout_idx (position,desktop_row,is_active,start_at,end_at),
  INDEX ads_banners_listing_idx (listing_id),
  INDEX ads_banners_seller_idx (seller_id),
  INDEX ads_banners_lifecycle_idx (lifecycle_status,start_at,end_at,reservation_expires_at),
  INDEX ads_banners_payment_idx (payment_status,lifecycle_status)
  ,INDEX ads_banners_experiment_idx (experiment_key,performance_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ads_slots (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  slot_key VARCHAR(64) NOT NULL,
  label VARCHAR(160) NOT NULL,
  page_type VARCHAR(64) NOT NULL,
  placement_description VARCHAR(300) NOT NULL,
  desktop_capacity INT NOT NULL DEFAULT 1,
  mobile_capacity INT NOT NULL DEFAULT 1,
  mobile_behavior ENUM('stack','hide','single','scroll') NOT NULL DEFAULT 'stack',
  recommended_size VARCHAR(80) NULL,
  aspect_ratio VARCHAR(32) NULL,
  source_types JSON NOT NULL,
  delivery_mode ENUM('fixed','rotation') NOT NULL DEFAULT 'fixed',
  base_daily_price DECIMAL(12,2) NOT NULL DEFAULT 100,
  traffic_multiplier DECIMAL(6,3) NOT NULL DEFAULT 1,
  visibility_multiplier DECIMAL(6,3) NOT NULL DEFAULT 1,
  desktop_multiplier DECIMAL(6,3) NOT NULL DEFAULT 1,
  mobile_multiplier DECIMAL(6,3) NOT NULL DEFAULT 1,
  is_active TINYINT NOT NULL DEFAULT 1,
  display_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY ads_slots_key_uq (slot_key),
  INDEX ads_slots_active_idx (is_active,display_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ads_targets (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  banner_id INT NOT NULL,
  scope_type ENUM('global','page_type','city','district','product','category','seller','listing') NOT NULL,
  scope_value VARCHAR(190) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY ads_targets_unique (banner_id,scope_type,scope_value),
  INDEX ads_targets_lookup_idx (scope_type,scope_value,banner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
