-- =============================================================
-- FILE: 80_custom_pages_core_seed.sql
-- Kaman Ilan - Core static pages (TR, dynamic module_key)
-- =============================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';

INSERT INTO `custom_pages`
(
  `id`,
  `title`,
  `slug`,
  `locale`,
  `module_key`,
  `content`,
  `image_url`,
  `storage_asset_id`,
  `alt`,
  `meta_title`,
  `meta_description`,
  `is_published`,
  `created_at`,
  `updated_at`
)
VALUES
(
  UUID(),
  'Hakkımızda',
  'hakkimizda',
  'tr',
  'about',
  JSON_OBJECT('html', CONCAT(
    '<section class="container mx-auto px-4 py-8">',
      '<h1 class="text-3xl md:text-4xl font-bold text-slate-900 mb-4">Kaman İlan Hakkında</h1>',
      '<p class="text-slate-700 leading-relaxed mb-6">',
        '<strong>Kaman İlan</strong>, alım-satım ve kiralama süreçlerinde müşterilerine ',
        '<strong>şeffaf, güvenilir ve hızlı</strong> hizmet sunmayı hedefleyen bir ilan platformudur.',
        ' Bölgenizin dinamiklerini bilen ekibimizle; emlak, hayvan, araç ve köy ürünleri kategorilerinde ',
        '<em>doğru fiyatlama</em>, <em>pazarlama</em> ve <em>işlem yönetimi</em> sağlıyoruz.',
      '</p>',
      '<div class="grid md:grid-cols-2 gap-6">',
        '<div class="bg-white border border-slate-200 rounded-xl p-6 shadow-sm">',
          '<h2 class="text-xl font-semibold text-slate-900 mb-3">Ne Yapıyoruz?</h2>',
          '<ul class="space-y-2 text-slate-700">',
            '<li>• İlan performans analizi ve emsal analizi</li>',
            '<li>• Profesyonel ilan sunumu ve hedefli pazarlama</li>',
            '<li>• Alıcı/kiracı aday yönetimi ve randevu organizasyonu</li>',
            '<li>• Sözleşme, tapu ve işlem takibi</li>',
          '</ul>',
        '</div>',
        '<div class="bg-white border border-slate-200 rounded-xl p-6 shadow-sm">',
          '<h2 class="text-xl font-semibold text-slate-900 mb-3">Neden Kaman İlan?</h2>',
          '<ul class="space-y-2 text-slate-700">',
            '<li>• Şeffaf süreç ve düzenli bilgilendirme</li>',
            '<li>• Müşteri odaklı danışmanlık yaklaşımı</li>',
            '<li>• Bölgesel uzmanlık ve veri temelli karar</li>',
            '<li>• Hızlı iletişim ve güçlü takip</li>',
          '</ul>',
        '</div>',
      '</div>',
      '<div class="mt-8 bg-slate-50 border border-slate-200 rounded-xl p-6">',
        '<p class="text-slate-700 m-0">',
          '<strong>Hedefimiz:</strong> İlanınız için en doğru stratejiyi belirlemek ve ',
          'ilan yayını ve iletişim sürecini güvenle tamamlamaktır.',
        '</p>',
      '</div>',
    '</section>'
  )),
  'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1400&q=80',
  NULL,
  'Kaman İlan - Hakkımızda',
  'Hakkımızda - Kaman İlan | Güvenilir İlan Platformu',
  'Kaman İlan: emlak, hayvan, araç ve köy ürünleri kategorilerinde şeffaf süreç, doğru fiyatlama ve güçlü ilan yönetimi sunar.',
  1,
  NOW(3),
  NOW(3)
),
(
  UUID(),
  'Gizlilik Politikası',
  'gizlilik-politikasi',
  'tr',
  'kvkk',
  JSON_OBJECT('html',
    '<section><h1>Gizlilik Politikası</h1><p>Kaman İlan, kişisel verilerin korunmasını öncelik kabul eder.</p><p>Toplanan veriler yalnızca hizmet sunumu, güvenlik ve yasal yükümlülükler kapsamında işlenir.</p></section>'
  ),
  NULL,
  NULL,
  'Gizlilik Politikası',
  'Gizlilik Politikası - Kaman İlan',
  'Kaman İlan gizlilik politikası ve veri işleme esasları.',
  1,
  NOW(3),
  NOW(3)
),
(
  UUID(),
  'Kullanım Koşulları',
  'kullanim-kosullari',
  'tr',
  'contract',
  JSON_OBJECT('html',
    '<section><h1>Kullanım Koşulları</h1><p>Platformu kullanan tüm kullanıcılar ilan yayın kurallarını ve yürürlükteki mevzuatı kabul eder.</p><p>Yanıltıcı içerik, yasaklı ürün/hizmet ilanı ve hak ihlali içeren paylaşımlar kaldırılır.</p></section>'
  ),
  NULL,
  NULL,
  'Kullanım Koşulları',
  'Kullanım Koşulları - Kaman İlan',
  'Kaman İlan kullanım koşulları ve ilan yayın kuralları.',
  1,
  NOW(3),
  NOW(3)
),
(
  UUID(),
  'Kalite Politikamız',
  'kalite-politikamiz',
  'tr',
  'quality',
  JSON_OBJECT('html', CONCAT(
    '<section class="container mx-auto px-4 py-8">',
      '<h1 class="text-3xl md:text-4xl font-bold text-slate-900 mb-4">Kalite Politikamız</h1>',
      '<p class="text-slate-700 mb-8">',
        'Kaman İlan olarak hizmet kalitemizi; <strong>şeffaflık</strong>, <strong>doğru bilgi</strong> ve ',
        '<strong>düzenli süreç yönetimi</strong> üzerine kurarız.',
      '</p>',
      '<div class="bg-gradient-to-br from-slate-50 to-blue-50 p-8 rounded-xl border-l-4 border-blue-600 shadow-sm mb-8">',
        '<h2 class="text-2xl text-slate-900 mb-6">🏆 Hizmet Standartlarımız</h2>',
        '<div class="space-y-5 text-slate-700">',
          '<p>',
            '<strong>Doğru fiyatlama</strong> için emsal analizi, bölgesel trendler ve mülk özelliklerini birlikte değerlendiririz. ',
            'İlan sunumunda <em>kaliteli içerik</em> ve <em>doğru konum bilgisi</em> ile güven veririz.',
          '</p>',
          '<p>',
            'Süreç boyunca müşterilerimizi düzenli bilgilendirir; görüşme, teklif ve sözleşme adımlarını ',
            '<strong>net ve izlenebilir</strong> şekilde yönetiriz.',
          '</p>',
        '</div>',
      '</div>',
      '<div class="bg-white border border-slate-200 p-8 rounded-xl shadow-sm mb-8">',
        '<h2 class="text-xl text-blue-800 mb-6">🔍 Kalite Kontrol Sürecimiz</h2>',
        '<div class="grid md:grid-cols-2 gap-6">',
          '<div class="space-y-4">',
            '<div class="flex items-start"><span class="w-6 h-6 bg-slate-900 rounded-full flex items-center justify-center mr-3 text-white text-xs mt-1 shrink-0">1</span><div><h3 class="text-sm font-semibold text-slate-900 mb-1">Ön Analiz</h3><p class="text-xs text-slate-600">Emsal, fiyat aralığı ve satış/kiralama stratejisi</p></div></div>',
            '<div class="flex items-start"><span class="w-6 h-6 bg-slate-900 rounded-full flex items-center justify-center mr-3 text-white text-xs mt-1 shrink-0">2</span><div><h3 class="text-sm font-semibold text-slate-900 mb-1">Portföy Hazırlığı</h3><p class="text-xs text-slate-600">İlan metni, görseller, konum ve temel bilgiler</p></div></div>',
            '<div class="flex items-start"><span class="w-6 h-6 bg-slate-900 rounded-full flex items-center justify-center mr-3 text-white text-xs mt-1 shrink-0">3</span><div><h3 class="text-sm font-semibold text-slate-900 mb-1">Aday Yönetimi</h3><p class="text-xs text-slate-600">Görüşmeler, talepler, geri bildirim ve eleme</p></div></div>',
          '</div>',
          '<div class="space-y-4">',
            '<div class="flex items-start"><span class="w-6 h-6 bg-blue-600 rounded-full flex items-center justify-center mr-3 text-white text-xs mt-1 shrink-0">4</span><div><h3 class="text-sm font-semibold text-slate-900 mb-1">Teklif ve Müzakere</h3><p class="text-xs text-slate-600">Şeffaf pazarlık yönetimi ve net bilgilendirme</p></div></div>',
            '<div class="flex items-start"><span class="w-6 h-6 bg-blue-600 rounded-full flex items-center justify-center mr-3 text-white text-xs mt-1 shrink-0">5</span><div><h3 class="text-sm font-semibold text-slate-900 mb-1">Sözleşme Süreci</h3><p class="text-xs text-slate-600">Evrak kontrol, sözleşme koordinasyonu</p></div></div>',
            '<div class="flex items-start"><span class="w-6 h-6 bg-blue-600 rounded-full flex items-center justify-center mr-3 text-white text-xs mt-1 shrink-0">6</span><div><h3 class="text-sm font-semibold text-slate-900 mb-1">Teslim ve Takip</h3><p class="text-xs text-slate-600">Teslim adımı ve memnuniyet takibi</p></div></div>',
          '</div>',
        '</div>',
      '</div>',
      '<div class="bg-gradient-to-r from-slate-900 to-blue-700 text-white p-8 rounded-xl shadow-sm">',
        '<h2 class="text-xl mb-4">🤝 Kalite Taahhüdümüz</h2>',
        '<p class="text-white/95">',
          'Her işlemde <strong>doğru bilgi</strong>, <strong>şeffaf iletişim</strong> ve <strong>düzenli takip</strong> ile ',
          'müşteri memnuniyetini en üst seviyede tutmayı taahhüt ederiz.',
        '</p>',
      '</div>',
    '</section>'
  )),
  'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80',
  NULL,
  'Kaman İlan - Kalite Politikası',
  'Kalite Politikamız - Kaman İlan | Şeffaf ve Veri Temelli Hizmet',
  'Kaman İlan kalite politikası: doğru fiyatlama, güvenilir ilan sunumu, düzenli süreç yönetimi ve müşteri memnuniyeti odaklı danışmanlık.',
  1,
  NOW(3),
  NOW(3)
),
(
  UUID(),
  'Misyonumuz - Vizyonumuz',
  'misyon-vizyon',
  'tr',
  'about',
  JSON_OBJECT('html', CONCAT(
    '<section class="container mx-auto px-4 py-8">',
      '<h1 class="text-3xl md:text-4xl font-bold text-slate-900 mb-4">Misyonumuz - Vizyonumuz</h1>',
      '<p class="text-slate-700 mb-8">',
        'Kaman İlan olarak ilan süreçlerini daha <strong>anlaşılır</strong>, daha <strong>güvenli</strong> ve ',
        'daha <strong>verimli</strong> hale getirmek için çalışıyoruz.',
      '</p>',
      '<div class="grid grid-cols-1 gap-8">',
        '<div class="bg-gradient-to-br from-slate-50 to-slate-100 p-6 rounded-xl shadow-sm border border-slate-200">',
          '<div class="flex items-center mb-4">',
            '<div class="w-10 h-10 bg-slate-900 rounded-full text-white flex items-center justify-center mr-3">🎯</div>',
            '<h2 class="text-2xl text-slate-900 m-0">Misyonumuz</h2>',
          '</div>',
          '<div class="space-y-4 text-slate-700">',
            '<p>',
              '<strong>Şeffaf ve güvenilir danışmanlık</strong> yaklaşımıyla, satıcı ve alıcıyı doğru bilgilerle buluşturmak; ',
              '<em>doğru fiyatlama</em>, <em>doğru pazarlama</em> ve <em>doğru iletişim</em> ile süreci yönetmek.',
            '</p>',
            '<p>',
              'Her ilanı veri odaklı analiz ederek, ilanın potansiyelini doğru anlatmak ve iletişim sürecini ',
              '<strong>hızlı, düzenli ve güvenli</strong> şekilde sonuçlandırmak.',
            '</p>',
          '</div>',
        '</div>',
        '<div class="bg-gradient-to-br from-blue-50 to-blue-100 p-6 rounded-xl shadow-sm border border-blue-200">',
          '<div class="flex items-center mb-4">',
            '<div class="w-10 h-10 bg-blue-600 rounded-full text-white flex items-center justify-center mr-3">🌟</div>',
            '<h2 class="text-2xl text-blue-800 m-0">Vizyonumuz</h2>',
          '</div>',
          '<div class="space-y-4 text-slate-700">',
            '<p>',
              '<strong>Bölgesinde örnek gösterilen</strong> bir ilan platformu markası olmak; ',
              'müşteri deneyimini teknoloji ve disiplinli süreç yönetimiyle güçlendirmek.',
            '</p>',
            '<p>',
              'İlan ekosisteminde <em>güven</em> ve <em>şeffaflık</em> standartlarını yükselterek, ',
              'uzun vadeli müşteri ilişkileri kurmak.',
            '</p>',
          '</div>',
        '</div>',
        '<div class="grid sm:grid-cols-2 gap-4">',
          '<div class="bg-white border-l-4 border-slate-900 p-4 rounded-r-lg shadow-sm">',
            '<h3 class="text-slate-900 font-semibold mb-2">📍 Bölgesel Uzmanlık</h3>',
            '<ul class="text-sm text-slate-700 space-y-1">',
              '<li>• Piyasa analizi ve emsal karşılaştırma</li>',
              '<li>• Doğru fiyatlama ve strateji</li>',
              '<li>• Etkin ilan ve sunum yönetimi</li>',
            '</ul>',
          '</div>',
          '<div class="bg-white border-l-4 border-blue-600 p-4 rounded-r-lg shadow-sm">',
            '<h3 class="text-blue-800 font-semibold mb-2">🤝 Müşteri Deneyimi</h3>',
            '<ul class="text-sm text-slate-700 space-y-1">',
              '<li>• Düzenli bilgilendirme</li>',
              '<li>• Hızlı iletişim ve takip</li>',
              '<li>• Güvenli işlem süreçleri</li>',
            '</ul>',
          '</div>',
        '</div>',
      '</div>',
    '</section>'
  )),
  'https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=1400&q=80',
  NULL,
  'Kaman İlan - Misyon Vizyon',
  'Misyonumuz ve Vizyonumuz - Kaman İlan | Şeffaf İlan Süreci',
  'Kaman İlan misyonu: doğru fiyatlama, profesyonel pazarlama, güvenli süreç. Vizyon: bölgede örnek gösterilen, müşteri deneyimi güçlü ilan markası.',
  1,
  NOW(3),
  NOW(3)
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `module_key` = VALUES(`module_key`),
  `content` = VALUES(`content`),
  `image_url` = VALUES(`image_url`),
  `storage_asset_id` = VALUES(`storage_asset_id`),
  `alt` = VALUES(`alt`),
  `meta_title` = VALUES(`meta_title`),
  `meta_description` = VALUES(`meta_description`),
  `is_published` = VALUES(`is_published`),
  `updated_at` = VALUES(`updated_at`);
